---
title: "aFC across tissues"
output: html_notebook
---

For genes that are eGenes in multiple tissues, compare aFC of top eQTLs to see if this supports real tissue specificity vs. stochasticity.

```{r}
library(tidyverse)

codes <- read_tsv("../methods.txt", col_types = "cccccc")

eqtls_all <- read_tsv("../data/eqtls.txt", col_types = "ccciiddddd") %>%
    filter(code %in% str_c(c("A", "I", "L", "P", "V"), "CCT")) %>%
    left_join(codes, by = "code") %>%
    mutate(gene_rank = fct_reorder(gene_id, log2_aFC_eQTL, mean) %>% as.integer()) %>%
    group_by(gene_id) %>%
    mutate(consistent = max(log2_aFC_eQTL) - min(log2_aFC_eQTL) <= 1) %>%
    ungroup()
eqtls <- eqtls_all %>%
    filter(qval < 0.05) %>%
    mutate(gene_rank = fct_reorder(gene_id, log2_aFC_eQTL, mean) %>% as.integer()) %>%
    group_by(gene_id) %>%
    mutate(consistent = max(log2_aFC_eQTL) - min(log2_aFC_eQTL) <= 1) %>%
    ungroup()
```

```{r}
eqtls %>%
    ggplot(aes(x = gene_rank, y = log2_aFC_eQTL, color = consistent)) +
    geom_point(size = 0.25, alpha = 0.5) +
    theme_minimal() +
    xlab("eGenes ranked by mean aFC across tissues")
```

```{r}
eqtls_all %>%
    ggplot(aes(x = gene_rank, y = log2_aFC_eQTL, color = consistent)) +
    geom_point(size = 0.25, alpha = 0.5) +
    theme_minimal() +
    xlab("All genes ranked by mean aFC across tissues")
```

```{r}
eqtls_all %>%
    filter(!is.na(log2_aFC_eQTL)) %>%
    group_by(gene_rank) %>%
    summarise(mean_log2_aFC = mean(log2_aFC_eQTL),
              stdev_log2_aFC = sd(log2_aFC_eQTL),
              consistent = any(consistent),
              .groups = "drop") %>%
    ggplot(aes(x = mean_log2_aFC, y = stdev_log2_aFC, color = consistent)) +
    geom_point(size = 0.25, alpha = 0.5)
```

```{r}
eqtls_all %>%
    filter(!is.na(log2_aFC_eQTL)) %>%
    group_by(gene_rank) %>%
    summarise(abs_mean_log2_aFC = abs(mean(log2_aFC_eQTL)),
              consistent = any(consistent),
              .groups = "drop") %>%
    ggplot(aes(x = abs_mean_log2_aFC, fill = consistent)) +
    geom_density(alpha = 0.5) +
    ggtitle("All genes")

eqtls %>%
    filter(!is.na(log2_aFC_eQTL)) %>%
    group_by(gene_rank) %>%
    summarise(abs_mean_log2_aFC = abs(mean(log2_aFC_eQTL)),
              consistent = any(consistent),
              .groups = "drop") %>%
    ggplot(aes(x = abs_mean_log2_aFC, fill = consistent)) +
    geom_density(alpha = 0.5) +
    ggtitle("eGenes")

eqtls_all %>%
    filter(!is.na(log2_aFC_eQTL)) %>%
    group_by(gene_rank) %>%
    summarise(abs_mean_log2_aFC = abs(mean(log2_aFC_eQTL)),
              consistent = any(consistent),
              .groups = "drop") %>%
    ggplot(aes(x = consistent, y = abs_mean_log2_aFC)) +
    geom_boxplot() +
    coord_flip() +
    ggtitle("All genes")

eqtls %>%
    filter(!is.na(log2_aFC_eQTL)) %>%
    group_by(gene_rank) %>%
    summarise(abs_mean_log2_aFC = abs(mean(log2_aFC_eQTL)),
              consistent = any(consistent),
              .groups = "drop") %>%
    ggplot(aes(x = consistent, y = abs_mean_log2_aFC)) +
    geom_boxplot() +
    coord_flip() +
    ggtitle("eGenes")
```

